import time
import config
import day_four_funcs

type_text = config.type_text

def day_four():
    type_text("...")
    time.sleep(1)
    type_text("...")
    time.sleep(1)
    type_text("...")
    time.sleep(1)
    type_text("...")
    time.sleep(1)
    type_text("You wake up early and head to the kitchens for some early sustenance.")
    time.sleep(1)
    type_text("Investigating certainly puts a fire in your belly!")
    time.sleep(1)
    type_text("One by one, the other guests wake up, and you gather everyone in the drawing room.")
    time.sleep(1)
    type_text("The time has come to reveal the truth.")
    time.sleep(1)
    type_text("Tension is thick in the air.")
    time.sleep(1)
    type_text("Before you reveal anything, there is one final chance to ask guests questions.")
    time.sleep(1)
    type_text("The storm outside has grown fiercer, rain lashing against the windows of the drawing room.")
    time.sleep(1)
    type_text("All the suspects are gathered, the tension palpable. ")
    time.sleep(1)
    type_text("You know one of them is a killer, and soon you'll make your accusation.")
    time.sleep(1)
    type_text("But first, you'll give one person a final chance to speak.")
    day_four_funcs.final_interviews()
    type_text("The time has come for you to make your accusation.")
    time.sleep(1)
    type_text("Looking around the room, you see guilty knowledge, fear, and desperation in various faces.")
    time.sleep(1)
    type_text("But only one person actually plunged that Egyptian dagger into Lord Hugo's back.")
    time.sleep(1)
    type_text("Who is guilty and who is innocent?")
    time.sleep(1)
    type_text("...")
    time.sleep(1)
    type_text("...")
    time.sleep(1)
    type_text("...")
    time.sleep(1)
    type_text("...")
    time.sleep(1)
    type_text("It's time to decide.")
    day_four_funcs.accusation()
    exit()
